POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "admin12@admin.com",
    "password": "admin1234"
}

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "admin1222@admin2123.com",
    "password": "admin1234",
    "firstName": "Admin",
    "lastName": "Admin"
}