### Variables
@baseUrl = http://localhost:5000
@userId = 67603229d67cb2d13a630884
@instrumentId = 675bf1b7979320c15d93c39a
@applicationId = 675bf1b7979320c15d93c39a

### Login first to get token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admins@admin.com",
    "password": "admin1234"
}

###
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluc0BhZG1pbi5jb20iLCJzdWIiOiI2NzYxODhmNGNmNTkyNGI4ZTVlOTM1OWMiLCJmaXJzdE5hbWUiOiJBZG1pbiIsImxhc3ROYW1lIjoiQWRtaW4iLCJpYXQiOjE3MzQ0NDYxMTcsImV4cCI6MTczNDUzMjUxN30.0rF2IEzCBemAJB2z1pNhTpKtKSL7_0N9CVJs628wi3I

### Create user detail
POST {{baseUrl}}/user-details
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": "{{userId}}",
  "address": "123 Test Street",
  "description": "Test user description",
  "instrumentId": "{{instrumentId}}",
  "applicationId": "{{applicationId}}",
  "isOpenToWork": true,
  "lastLoggedIn": null
}

### Get user detail by userId
GET {{baseUrl}}/user-details/{{userId}}
Authorization: Bearer {{authToken}}

### Update user detail
PATCH {{baseUrl}}/user-details/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "address": "456 Updated Street",
  "description": "Updated description",
  "instrumentId": "{{instrumentId}}",
  "applicationId": "{{applicationId}}",
  "isOpenToWork": true,
  "lastLoggedIn": "2024-12-16T13:00:00.000Z"
}

### Delete user detail
DELETE {{baseUrl}}/user-details/{{userId}}
Authorization: Bearer {{authToken}}
